### PR TITLE
Add a file for Boise, the hometown of most of us.

### PR DESCRIPTION
**Pull request by dereckrx**
@ratsark, do you use present tense for your commit messages? I always read that thats the way your supposed to write them but I never have.

### CODE REVIEW

**Comment by bbaughn** [comment]
The branch name should be feature/add_boise or just feature/boise.  Not sure if that can be changed?

**Comment by ratsark** [comment]
Dereck, I have no idea what you mean when asking whether I use present tense for commit messages; I've never discussed the grammatical style of commit messages before. I describe what the CL does. Do you have some suggestion as to how I might better write CL descriptions?

**Comment by ratsark** [comment]
Also, please ignore this pull request. I issued another from a different branch, and want to go through the process of getting my changes merged.

**Comment by bbaughn** [comment]
You can close a pull request by hitting the "Close" button down by the Comment button on the pull request's page.

As for comment messages I think dereck just means a lot of people including me write in the past tense "Added a bunch of files" but I don't know what's propa.

**Comment by ratsark** [comment]
Ah, yes, I try to write my commit descriptions in the present tense because they describe what the change DOES - the change hasn't DONE anything at the point at which you're describing it. I guess that's how I think about it anyway.

**Pull request closed without merging**
